[features]
resolution = true
skip-lint = false

[programs.localnet]
predict_duel = "8aMfhVJxNZeGjgDg38XwdpMqDdrsvM42RPjF67DQ8VVe"

[programs.devnet]
predict_duel = "8aMfhVJxNZeGjgDg38XwdpMqDdrsvM42RPjF67DQ8VVe"

[programs.mainnet]
predict_duel = "8aMfhVJxNZeGjgDg38XwdpMqDdrsvM42RPjF67DQ8VVe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
